name: vpn_telegram_bot
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  dart_printf: ^0.6.0
  get_it: ^7.2.0
  shelf_router: ^1.1.3
  teledart: ^0.3.4
  yaml: ^3.1.0
  yaml_writer: 1.0.1
